---
# Name of the environment (e.g. dev/test/prod)
environment: prod

# Azure region where the solution needs to be deployed
location: westeurope

# Azure Subscription ID
subscription: 7example-abcd-1234-pqrs-examplec5db2

# Azure AD B2C Tenant Name
aadB2cOrg: suruku

# Azure AD B2C User Flow Name for Sign Up and Sign In
aadB2cUserFlow: B2C_1_us_sisu

# Azure AD B2C App Client Id of API
aadB2cApiClientId: bexample-abcd-1234-pqrs-examplef9a45

# Azure AD B2C App Client Id of Single Page Application (SPA)
aadB2cSpaClientId: fexample-abcd-1234-pqrs-example6cd6a

# URL that should be used for shorterning
shortUrl: https://az.pprakash.me/

# Write scope for API
writeScope: https://suruku.onmicrosoft.com/shorten-url/API.Write

# Read scope for API
readScope: https://suruku.onmicrosoft.com/shorten-url/API.Read